#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['quark_sphinx_theme',
 'quark_sphinx_theme.ext',
 'quark_sphinx_theme.ext.html_rewrite']

package_data = \
{'': ['*'], 'quark_sphinx_theme': ['quark/*', 'quark/static/*']}

install_requires = \
['sphinx >= 1.8']

extras_require = \
{'test': ['html5lib', 'tinycss']}

entry_points = \
{'sphinx.html_themes': ['quark = quark_sphinx_theme']}

setup(name='quark-sphinx-theme',
      version='0.6.0',
      description='A Sphinx theme designed for QTextBrowser',
      author='Felix Krull',
      author_email='f_krull@gmx.de',
      url='https://gitlab.com/fkrull/quark-sphinx-theme',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>= 3.5',
     )
